### ISSUE TITLE
critical alarm found, but checkoutput: no alarms found

### ISSUE THREAD

**Issue by tobias-weiss** [usolved/check_usolved_vsphere_alarms#3] opened 2017-04-26 12:51 UTC
Hello,

we have quite a number of notifications where a critical problem is indicated with a alert like this:
	
`ISVMSM192 vCenterServer: vCenter Alarms
Critical - 1 alarms found. View extended output for more information.`

But the corresponding plugin output says: 

`OK - No alarms found.`

This sometimes occurs several times a day, but I do not see any pattern in intervals, time etc.

I exported the events from the vCenter and humbled over some odds:

1. Session Times (in general) are extremely long, about 2-3 hours. Look at the time delta between logon and logoff. 
Is this normal? Does this has an impact on the vCenter?

`info      4/26/2017 11:49:36 AM   VSPHERE.LOCAL\icingamon User VSPHERE.LOCAL\icingamon@172.85.23.39 logged out (login time: Wednesday, April 26, 2017 9:19:22 AM, number of API invocations: 1, user agent: VI Perl)`

2. Script seems not to recognize state changes during check time

Here is an example, when crtitical state is indicated liek above, but plugin output only says: " OK - No alarms found."

`info      4/26/2017 9:19:50 AM                            Alarm 'Data Service Health Alarm' on Datencenter changed from Yellow to Green
info      4/26/2017 9:19:48 AM                            vmware-dataservice-sca status changed from yellow to green
info      4/26/2017 9:19:45 AM                            Alarm 'Virtual machine CPU usage' on VTS184PS sent 
email to some@contacts.org;
info      4/26/2017 9:19:45 AM                            Alarm 'Virtual machine CPU usage' on VTS184PS triggered an action
info      4/26/2017 9:19:45 AM                            Alarm 'Virtual machine CPU usage' on VTS184PS changed from Green to Red
info      4/26/2017 9:19:43 AM    VSPHERE.LOCAL\icingamon User VSPHERE.LOCAL\icingamon@192.168.32.9 logged in as VI Perl
info      4/26/2017 9:19:37 AM    VSPHERE.LOCAL\icingamon User VSPHERE.LOCAL\icingamon@172.85.23.39 logged out (login time: Wednesday, April 26, 2017 6:49:23 AM, number of API invocations: 1, user agent: VI Perl)
info      4/26/2017 9:19:37 AM    VSPHERE.LOCAL\icingamon User VSPHERE.LOCAL\icingamon@172.85.23.39 logged in as VI Perl
info      4/26/2017 9:19:36 AM    VSPHERE.LOCAL\icingamon User VSPHERE.LOCAL\icingamon@192.168.32.9 logged out (login time: Wednesday, April 26, 2017 6:46:52 AM, number of API invocations: 1, user agent: VI Perl)
info      4/26/2017 9:19:23 AM    VSPHERE.LOCAL\icingamon User VSPHERE.LOCAL\icingamon@172.85.23.39 logged out (login time: Wednesday, April 26, 2017 6:44:40 AM, number of API invocations: 2, user agent: VI Perl)
info      4/26/2017 9:19:22 AM    VSPHERE.LOCAL\icingamon User VSPHERE.LOCAL\icingamon@172.85.23.39 logged in as VI Perl
info      4/26/2017 9:18:13 AM                            Alarm 'Data Service Health Alarm': an SNMP trap for entity Datencenter was sent
info      4/26/2017 9:18:13 AM                            Alarm 'Data Service Health Alarm' on Datencenter triggered an action
info      4/26/2017 9:18:13 AM                            Alarm 'Data Service Health Alarm' on Datencenter changed from Green to Yellow
info      4/26/2017 9:18:13 AM                            Alarm 'vSphere Client Health Alarm': an SNMP trap for entity Datencenter was sent
info      4/26/2017 9:18:13 AM                            Alarm 'vSphere Client Health Alarm' on Datencenter triggered an action
info      4/26/2017 9:18:13 AM                            Alarm 'vSphere Client Health Alarm' on Datencenter changed from Green to Yellow
info      4/26/2017 9:18:12 AM                            vmware-dataservice-sca status changed from green to yellow`

This is actually a patern. Short before login the state is degraded from green to yellow for some reason, but returns green during check cycle and in consequence the output is "OK - No alarms found."

Hope these infos will provide you meaningful information on the issue. Please do not hesitate to request further information on this. Thank you.

**Comment by tobias-weiss** [comment] 2017-04-28 09:54
Just to let you know: I checked an another vSpere enviorenment, in which we do not have problems with suddes status changes. The time delta betwen logon logoff, is with about 30-40 minutes long, but not as much as the up to three ours which I saw in the first enviorenment .

**Comment by usolved** [comment] 2017-04-28 11:26
Thanks for your detailed bug report.

I just have access to one vSphere environment but I'll have a look on how it behaves there and give feedback (hopefully next week). Maybe the script doesn't end the user sessions and at some point vCenter kills the user session like a time out.

**Comment by tobias-weiss** [comment] 2017-04-28 13:50
Thanks for looking into it. I just want you to know that from my perspective there is no need for rush. I will be on vacation the next two weeks. :)

**Comment by usolved** [comment] 2017-05-18 12:15
Not that easy to answer to be honest and I don't have a solution right now.

I tried to reproduce/monitor the user login session (vcenter 5.5). But every time I've executed the plugin the session has been disconnected directly after the script finished (as intended). I also tried the plugin on a remote poller that checks another vcenter (v6) but with the same result.

In our environment we also use check_vmware_esx.pl. After every execution the session is still active but I guess it's because the plugin uses session files to reduce the amount of login/logout events.

Do you also use other icinga plugins that uses the VMWare Perl SDK with the same user?

Would be interesting to know if other user have similar problems.

**Comment by usolved** [comment] 2020-11-10 20:28
I'll close this issue for now since there was no more feedback on the topic (or other users with a similar issue). If this can be reproduced I'm happy to re-open this issue again.

**Closed as completed by usolved** 2020-11-10 20:28 UTC
